version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:16-alpine # Use an official PostgreSQL image
    environment:
      POSTGRES_DB: hello
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: insecure
    ports:
      - "5432:5432" # Map PostgreSQL port to the host machine
    volumes:
      - hello_pgdata:/var/lib/postgresql/data

  app:
    build:
      context: hello
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres # Ensure that the database service is started first
    environment:
      PGDATABASE: hello
      PGUSER: demo
      PGPASSWORD: insecure
      PGHOST: postgres
      PGPORT: 5432

volumes:
  hello_pgdata:
    external: true
